# Generated by Django 4.1.2 on 2022-12-26 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puf_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FramTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(max_length=30)),
                ('temp', models.FloatField()),
                ('vol', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FramResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puf_server.framtests')),
            ],
        ),
    ]
