# Generated by Django 4.1.2 on 2022-12-26 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('puf_server', '0002_framtests_framresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='framtests',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
