# Generated by Django 4.1.2 on 2023-01-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puf_server', '0004_framtests_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=30)),
                ('voltage', models.FloatField()),
                ('temperture', models.FloatField()),
            ],
        ),
    ]
