# Generated by Django 4.1.2 on 2023-01-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puf_server', '0005_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='dataSetupTime',
            field=models.FloatField(default=15),
        ),
        migrations.AddField(
            model_name='tests',
            name='initialValue',
            field=models.CharField(default='0x55', max_length=10),
        ),
        migrations.AddField(
            model_name='tests',
            name='startAddress',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tests',
            name='stopAddress',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='tests',
            name='type',
            field=models.CharField(default='FRAM', max_length=100),
        ),
    ]
