# Generated by Django 4.1.2 on 2023-01-15 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puf_server', '0006_tests_datasetuptime_tests_initialvalue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='temperture',
            new_name='temperature',
        ),
    ]
