# Generated by Django 4.1.2 on 2023-01-19 17:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('puf_server', '0008_alter_tests_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('usedBy', models.CharField(max_length=50)),
                ('lastUse', models.DateTimeField(default=django.utils.timezone.now)),
                ('count', models.IntegerField(default=0)),
                ('testId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puf_server.tests')),
            ],
        ),
    ]
