# Generated by Django 4.1.2 on 2023-02-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puf_server', '0009_testoperations'),
    ]

    operations = [
        migrations.AddField(
            model_name='testoperations',
            name='fileName',
            field=models.CharField(default='a123.csv', max_length=50),
        ),
    ]
