# Generated by Django 4.1.2 on 2023-02-14 21:46

from django.db import migrations, models
import puf_server.models


class Migration(migrations.Migration):

    dependencies = [
        ('puf_server', '0010_testoperations_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to=puf_server.models.upload_path)),
            ],
        ),
    ]
