# Generated by Django 4.1.2 on 2023-02-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puf_server', '0011_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='type',
            new_name='testType',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
