# Generated by Django 4.1.2 on 2023-03-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puf_server', '0013_experiments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='dataSetupTime',
            field=models.CharField(default='15', max_length=50),
        ),
    ]
