# Generated by Django 4.1.2 on 2023-03-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puf_server', '0014_alter_tests_datasetuptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='testoperations',
            name='dataSetupTime',
            field=models.IntegerField(default=15),
        ),
    ]
