# Generated by Django 4.1.2 on 2023-03-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puf_server', '0015_testoperations_datasetuptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='testoperations',
            name='iteration',
            field=models.IntegerField(default=0),
        ),
    ]
