# Generated by Django 4.1.2 on 2023-04-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puf_server', '0016_testoperations_iteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testoperations',
            name='fileName',
            field=models.CharField(max_length=50),
        ),
    ]
