# Generated by Django 4.1.2 on 2023-04-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puf_server', '0017_alter_testoperations_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testoperations',
            name='fileName',
            field=models.CharField(default='123.csv', max_length=100),
        ),
    ]
