# Generated by Django 4.1.2 on 2023-06-01 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadReadLatencyMeasurmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('testType', models.CharField(max_length=100, null=True)),
                ('board', models.CharField(max_length=50, null=True)),
                ('memory', models.CharField(max_length=30, null=True)),
                ('fileName', models.CharField(default='default.csv', max_length=100)),
                ('file', models.FileField(default='default.csv', upload_to='uploaded_csv_files/')),
                ('initialValue', models.CharField(default='0x55', max_length=10)),
                ('startAddress', models.FloatField(default=0, null=True)),
                ('stopAddress', models.FloatField(default=100, null=True)),
                ('voltage', models.FloatField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('iteration', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('usedBy', models.CharField(default='Anonymous', max_length=50)),
                ('dataSetupTime', models.CharField(default='15', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadReliabilityMeasurmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('testType', models.CharField(max_length=100, null=True)),
                ('board', models.CharField(max_length=50, null=True)),
                ('memory', models.CharField(max_length=30, null=True)),
                ('fileName', models.CharField(default='default.csv', max_length=100)),
                ('file', models.FileField(default='default.csv', upload_to='uploaded_csv_files/')),
                ('initialValue', models.CharField(default='0x55', max_length=10)),
                ('startAddress', models.FloatField(default=0, null=True)),
                ('stopAddress', models.FloatField(default=100, null=True)),
                ('voltage', models.FloatField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('iteration', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('usedBy', models.CharField(default='Anonymous', max_length=50)),
                ('dataSetupTime', models.CharField(default='15', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadRowHammeringMeasurmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('testType', models.CharField(max_length=100, null=True)),
                ('board', models.CharField(max_length=50, null=True)),
                ('memory', models.CharField(max_length=30, null=True)),
                ('fileName', models.CharField(default='default.csv', max_length=100)),
                ('file', models.FileField(default='default.csv', upload_to='uploaded_csv_files/')),
                ('initialValue', models.CharField(default='0x55', max_length=10)),
                ('startAddress', models.FloatField(default=0, null=True)),
                ('stopAddress', models.FloatField(default=100, null=True)),
                ('voltage', models.FloatField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('iteration', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('usedBy', models.CharField(default='Anonymous', max_length=50)),
                ('dataSetupTime', models.CharField(default='15', max_length=50)),
                ('initialValue_2', models.CharField(default='0xAA', max_length=10)),
                ('rowOffset', models.IntegerField(default=1)),
                ('iterations', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadWriteLatencyMeasurmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('testType', models.CharField(max_length=100, null=True)),
                ('board', models.CharField(max_length=50, null=True)),
                ('memory', models.CharField(max_length=30, null=True)),
                ('fileName', models.CharField(default='default.csv', max_length=100)),
                ('file', models.FileField(default='default.csv', upload_to='uploaded_csv_files/')),
                ('initialValue', models.CharField(default='0x55', max_length=10)),
                ('startAddress', models.FloatField(default=0, null=True)),
                ('stopAddress', models.FloatField(default=100, null=True)),
                ('voltage', models.FloatField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('iteration', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('usedBy', models.CharField(default='Anonymous', max_length=50)),
                ('dataSetupTime', models.CharField(default='15', max_length=50)),
                ('initialValue_2', models.CharField(default='0xAA', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
