# Generated by Django 4.1.2 on 2023-07-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_measurments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadreadlatencymeasurmentmodel',
            old_name='memory',
            new_name='memoryLabel',
        ),
        migrations.RenameField(
            model_name='uploadreliabilitymeasurmentmodel',
            old_name='memory',
            new_name='memoryLabel',
        ),
        migrations.RenameField(
            model_name='uploadrowhammeringmeasurmentmodel',
            old_name='memory',
            new_name='memoryLabel',
        ),
        migrations.RenameField(
            model_name='uploadwritelatencymeasurmentmodel',
            old_name='memory',
            new_name='memoryLabel',
        ),
        migrations.AddField(
            model_name='uploadreadlatencymeasurmentmodel',
            name='memoryBrand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadreadlatencymeasurmentmodel',
            name='memoryModel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadreadlatencymeasurmentmodel',
            name='memoryType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uploadreliabilitymeasurmentmodel',
            name='memoryBrand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadreliabilitymeasurmentmodel',
            name='memoryModel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadreliabilitymeasurmentmodel',
            name='memoryType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uploadrowhammeringmeasurmentmodel',
            name='memoryBrand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadrowhammeringmeasurmentmodel',
            name='memoryModel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadrowhammeringmeasurmentmodel',
            name='memoryType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uploadwritelatencymeasurmentmodel',
            name='memoryBrand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadwritelatencymeasurmentmodel',
            name='memoryModel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadwritelatencymeasurmentmodel',
            name='memoryType',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
