# Generated by Django 4.1.2 on 2023-07-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TtyDeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=255)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
