# Generated by Django 4.1.2 on 2023-07-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_detection', '0002_ttydevicemodel_delete_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttydevicemodel',
            name='node',
        ),
        migrations.AddField(
            model_name='ttydevicemodel',
            name='device_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ttydevicemodel',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ttydevicemodel',
            name='device_port',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ttydevicemodel',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ttydevicemodel',
            name='is_removed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
