# Generated by Django 4.1.2 on 2023-07-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_detection', '0004_ttydevicemodel_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ttydevicemodel',
            old_name='is_removed',
            new_name='is_busy',
        ),
        migrations.AddField(
            model_name='ttydevicemodel',
            name='connected_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ttydevicemodel',
            name='is_connected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ttydevicemodel',
            name='device_port',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
