# Generated by Django 4.1.2 on 2023-07-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_evaluationtask_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationtask',
            name='metricsResult',
            field=models.JSONField(default=dict),
        ),
    ]
