# Generated by Django 4.1.2 on 2023-08-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_evaluationtask_metricsresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_ids', models.JSONField()),
                ('initial_value', models.TextField()),
                ('heatmap_binary_image', models.BinaryField()),
                ('evaluation_result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.evaluationtask')),
            ],
        ),
    ]
