# Generated by Django 4.1.2 on 2023-05-30 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadLatencyTestsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='defualt title', max_length=100)),
                ('testType', models.CharField(default='default test', max_length=100)),
                ('board', models.CharField(max_length=50, null=True)),
                ('memory', models.CharField(max_length=30, null=True)),
                ('initialValue', models.CharField(default='0x55', max_length=10)),
                ('startAddress', models.FloatField(default=0)),
                ('stopAddress', models.FloatField(default=100)),
                ('voltage', models.FloatField(default=3)),
                ('temperature', models.FloatField(default=23)),
                ('dataSetupTime', models.CharField(default='15', max_length=50)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReliabilityTestsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='defualt title', max_length=100)),
                ('testType', models.CharField(default='default test', max_length=100)),
                ('board', models.CharField(max_length=50, null=True)),
                ('memory', models.CharField(max_length=30, null=True)),
                ('initialValue', models.CharField(default='0x55', max_length=10)),
                ('startAddress', models.FloatField(default=0)),
                ('stopAddress', models.FloatField(default=100)),
                ('voltage', models.FloatField(default=3)),
                ('temperature', models.FloatField(default=23)),
                ('dataSetupTime', models.CharField(default='15', max_length=50)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RowHammeringTestsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='defualt title', max_length=100)),
                ('testType', models.CharField(default='default test', max_length=100)),
                ('board', models.CharField(max_length=50, null=True)),
                ('memory', models.CharField(max_length=30, null=True)),
                ('initialValue', models.CharField(default='0x55', max_length=10)),
                ('startAddress', models.FloatField(default=0)),
                ('stopAddress', models.FloatField(default=100)),
                ('voltage', models.FloatField(default=3)),
                ('temperature', models.FloatField(default=23)),
                ('dataSetupTime', models.CharField(default='15', max_length=50)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('initialValue_2', models.CharField(default='0xAA', max_length=10)),
                ('rowOffset', models.IntegerField(default=1)),
                ('iterations', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WriteLatencyTestsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='defualt title', max_length=100)),
                ('testType', models.CharField(default='default test', max_length=100)),
                ('board', models.CharField(max_length=50, null=True)),
                ('memory', models.CharField(max_length=30, null=True)),
                ('initialValue', models.CharField(default='0x55', max_length=10)),
                ('startAddress', models.FloatField(default=0)),
                ('stopAddress', models.FloatField(default=100)),
                ('voltage', models.FloatField(default=3)),
                ('temperature', models.FloatField(default=23)),
                ('dataSetupTime', models.CharField(default='15', max_length=50)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('initialValue_2', models.CharField(default='0xAA', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
