# Generated by Django 4.1.2 on 2023-06-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_writelatencymeasurmenttestsmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readlatencytestsmodel',
            old_name='memory',
            new_name='memoryLabel',
        ),
        migrations.RenameField(
            model_name='reliabilitytestsmodel',
            old_name='memory',
            new_name='memoryLabel',
        ),
        migrations.RenameField(
            model_name='rowhammeringtestsmodel',
            old_name='memory',
            new_name='memoryLabel',
        ),
        migrations.RenameField(
            model_name='writelatencytestsmodel',
            old_name='memory',
            new_name='memoryLabel',
        ),
        migrations.AddField(
            model_name='readlatencytestsmodel',
            name='memoryBrand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='readlatencytestsmodel',
            name='memoryModel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='readlatencytestsmodel',
            name='memoryType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reliabilitytestsmodel',
            name='memoryBrand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reliabilitytestsmodel',
            name='memoryModel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reliabilitytestsmodel',
            name='memoryType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rowhammeringtestsmodel',
            name='memoryBrand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rowhammeringtestsmodel',
            name='memoryModel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rowhammeringtestsmodel',
            name='memoryType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='writelatencytestsmodel',
            name='memoryBrand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='writelatencytestsmodel',
            name='memoryModel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='writelatencytestsmodel',
            name='memoryType',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
