# Generated by Django 4.1.2 on 2023-07-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_remove_readlatencytestsmodel_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readlatencytestsmodel',
            name='memoryBrand',
        ),
        migrations.RemoveField(
            model_name='readlatencytestsmodel',
            name='memoryLabel',
        ),
        migrations.RemoveField(
            model_name='readlatencytestsmodel',
            name='memoryModel',
        ),
        migrations.RemoveField(
            model_name='readlatencytestsmodel',
            name='memoryType',
        ),
        migrations.RemoveField(
            model_name='reliabilitytestsmodel',
            name='memoryBrand',
        ),
        migrations.RemoveField(
            model_name='reliabilitytestsmodel',
            name='memoryLabel',
        ),
        migrations.RemoveField(
            model_name='reliabilitytestsmodel',
            name='memoryModel',
        ),
        migrations.RemoveField(
            model_name='reliabilitytestsmodel',
            name='memoryType',
        ),
        migrations.RemoveField(
            model_name='rowhammeringtestsmodel',
            name='memoryBrand',
        ),
        migrations.RemoveField(
            model_name='rowhammeringtestsmodel',
            name='memoryLabel',
        ),
        migrations.RemoveField(
            model_name='rowhammeringtestsmodel',
            name='memoryModel',
        ),
        migrations.RemoveField(
            model_name='rowhammeringtestsmodel',
            name='memoryType',
        ),
        migrations.RemoveField(
            model_name='writelatencytestsmodel',
            name='memoryBrand',
        ),
        migrations.RemoveField(
            model_name='writelatencytestsmodel',
            name='memoryLabel',
        ),
        migrations.RemoveField(
            model_name='writelatencytestsmodel',
            name='memoryModel',
        ),
        migrations.RemoveField(
            model_name='writelatencytestsmodel',
            name='memoryType',
        ),
        migrations.AddField(
            model_name='readlatencymeasurmenttestsmodel',
            name='memoryBrand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='readlatencymeasurmenttestsmodel',
            name='memoryLabel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='readlatencymeasurmenttestsmodel',
            name='memoryModel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='readlatencymeasurmenttestsmodel',
            name='memoryType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reliabilitymeasurmenttestsmodel',
            name='memoryBrand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reliabilitymeasurmenttestsmodel',
            name='memoryLabel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reliabilitymeasurmenttestsmodel',
            name='memoryModel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reliabilitymeasurmenttestsmodel',
            name='memoryType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rowhammeringmeasurmenttestsmodel',
            name='memoryBrand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rowhammeringmeasurmenttestsmodel',
            name='memoryLabel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rowhammeringmeasurmenttestsmodel',
            name='memoryModel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rowhammeringmeasurmenttestsmodel',
            name='memoryType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='writelatencymeasurmenttestsmodel',
            name='memoryBrand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='writelatencymeasurmenttestsmodel',
            name='memoryLabel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='writelatencymeasurmenttestsmodel',
            name='memoryModel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='writelatencymeasurmenttestsmodel',
            name='memoryType',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
