# Generated by Django 4.1.2 on 2023-07-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_remove_readlatencytestsmodel_memorybrand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readlatencymeasurmenttestsmodel',
            name='boardLabel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='readlatencymeasurmenttestsmodel',
            name='boardName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='readlatencymeasurmenttestsmodel',
            name='boardSerial',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reliabilitymeasurmenttestsmodel',
            name='boardLabel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reliabilitymeasurmenttestsmodel',
            name='boardName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reliabilitymeasurmenttestsmodel',
            name='boardSerial',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rowhammeringmeasurmenttestsmodel',
            name='boardLabel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rowhammeringmeasurmenttestsmodel',
            name='boardName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rowhammeringmeasurmenttestsmodel',
            name='boardSerial',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='writelatencymeasurmenttestsmodel',
            name='boardLabel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='writelatencymeasurmenttestsmodel',
            name='boardName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='writelatencymeasurmenttestsmodel',
            name='boardSerial',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
