# Generated by Django 4.1.2 on 2023-08-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_readlatencymeasurmenttestsmodel_boardlabel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readlatencytestsmodel',
            name='elapsedTime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readlatencytestsmodel',
            name='iterations',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='reliabilitytestsmodel',
            name='elapsedTime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliabilitytestsmodel',
            name='iterations',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='rowhammeringtestsmodel',
            name='elapsedTime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writelatencytestsmodel',
            name='elapsedTime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writelatencytestsmodel',
            name='iterations',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
