# Generated by Django 4.1.2 on 2023-08-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_readlatencytestsmodel_elapsedtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readlatencytestsmodel',
            name='elapsedTime',
        ),
        migrations.RemoveField(
            model_name='reliabilitytestsmodel',
            name='elapsedTime',
        ),
        migrations.RemoveField(
            model_name='rowhammeringtestsmodel',
            name='elapsedTime',
        ),
        migrations.RemoveField(
            model_name='writelatencytestsmodel',
            name='elapsedTime',
        ),
        migrations.AddField(
            model_name='readlatencymeasurmenttestsmodel',
            name='elapsedTime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliabilitymeasurmenttestsmodel',
            name='elapsedTime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rowhammeringmeasurmenttestsmodel',
            name='elapsedTime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writelatencymeasurmenttestsmodel',
            name='elapsedTime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
