# Generated by Django 4.1.2 on 2023-10-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_remove_readlatencytestsmodel_elapsedtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowhammeringtestsmodel',
            name='HammeringIterations',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rowhammeringtestsmodel',
            name='iterations',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='writelatencytestsmodel',
            name='initialValue_2',
            field=models.CharField(default='0x55', max_length=10),
        ),
    ]
