# Generated by Django 4.1.2 on 2023-10-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_rowhammeringtestsmodel_hammeringiterations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowhammeringmeasurmenttestsmodel',
            name='HammeringIterations',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rowhammeringmeasurmenttestsmodel',
            name='initialValue_2',
            field=models.CharField(default='0xAA', max_length=10),
        ),
        migrations.AddField(
            model_name='rowhammeringmeasurmenttestsmodel',
            name='rowOffset',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='writelatencymeasurmenttestsmodel',
            name='initialValue_2',
            field=models.CharField(default='0x55', max_length=10),
        ),
    ]
